notifications:
  email: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libplot-dev plotutils
install: python setup.py install_data
script: python setup.py test
